config/routes.rb
Marysplace::Application.routes.draw do

  resources :organizations

  resources :client_notes


  namespace :api, defaults: { format: :json } do
    namespace :v0 do
      resources :checkins, only: [ :create ]
    end
  end

  resources :locations

  resources :messages

  resources :roles, only: [ :show ]

  resources :client_flags do
    member do
      get 'resolve'
      post 'resolve_store'
    end

    collection do
      get 'resolved'
      get 'unresolved'
    end
  end

  resources :checkins do
    collection do
      get 'selfcheck'
      put 'selfcheck_post'
      get 'today'
      get 'report/:year/:month/:day' => 'checkins#daily_report',
        constraints: {
          year: %r/\d{4}/,
          month: %r/\d\d?/,
          day: %r/\d\d?/
        },
        as: 'daily_report'
      get 'report/:year/:month' => 'checkins#monthly_report',
        constraints: {
          year: %r/\d{4}/,
          month: %r/\d\d?/,
        },
        as: 'monthly_report'
      get 'report/:year' => 'checkins#annual_report',
        constraints: {
          year: %r/\d{4}/,
        },
        as: 'annual_report'
    end
  end

  resources :points_entries

  resources :points_entry_types do
    collection do
      get 'search'
      get 'all'
      get 'unpaged'
    end

    member do
      get 'entry'
      get 'report/:year/:month/:day' => 'points_entry_types#report',
        constraints: {
          year: %r/\d{4}/,
          month: %r/\d\d?/,
          day: %r/\d\d?/
        },
        as: 'daily_report'
      get 'report/:year/:month' => 'points_entry_types#report',
        constraints: {
          year: %r/\d{4}/,
          month: %r/\d\d?/,
        },
        as: 'monthly_report'
      get 'report/:year' => 'points_entry_types#report',
        constraints: {
          year: %r/\d{4}/,
        },
        as: 'annual_report'
      get 'report'
    end
  end

  resources :clients do
    collection do
      get 'all'
      get 'search'
    end

    member do
      get 'barcode'
      get 'card'
      post 'checkin_code'
      get 'checkins'
      get 'entries'
      get 'entry'
      get 'flags'
      get 'notes'
      get 'purchases'
    end
  end

  get "welcome/index"
  resources :users, except: [ :destroy ] do
    member do
      get  'entries'
      post 'preference'
    end
  end

  resources :password_resets,
    except: [ :destroy ]

  resource :user_session, only: [ :new, :create, :destroy ]

  get 'login' => 'user_sessions#new', as: :login
  delete 'logout' => 'user_sessions#destroy', as: :logout

  root :to => 'welcome#index'
end

app/models/points_entry.rb
require 'pp'

# Records a gain or loss of incentive points for a client,
# along with information about the change
# (Examples: performed a chore, bailed on a chore, made a purchase)
class PointsEntry < ActiveRecord::Base
  belongs_to :client
  belongs_to :points_entry_type
  belongs_to :added_by,
    class_name: "User"
  belongs_to :location

  validates :added_by_id,
    presence: true
  validates :client_id,
    presence: true
  validates :points_entry_type_id,
    presence: true
  validates :location_id,
    presence: true
  validates :points_entered,
    presence: true
  validates :multiple,
    numericality: {
      equal_to: 1,
      message: "does not apply to negative point entries"
    },
    if:  Proc.new { |entry| entry.points_entered && entry.points_entered < 0 }
  validates :multiple,
    numericality: {
      greater_than: 0
    }

  default_scope { order 'performed_on DESC, id DESC' }

  scope :purchases, -> {
    joins(:points_entry_type).merge(PointsEntryType.purchase)
  }

  delegate :current_alias, :is_flagged, :can_shop?, :point_balance,
    to:        :client,
    prefix:    true,
    allow_nil: true
  delegate :login,
    to:     :added_by,
    prefix: true
  delegate :name, :default_points,
    to:        :points_entry_type,
    prefix:    'type',
    allow_nil: true
  delegate :name,
    to:     :location,
    prefix: true

  # Many PointsEntries were created before 'points_entered' was a thing.
  after_find do
    if self.points_entered.nil? or self.points_entered = 0
      self.points_entered = self.points / self.multiple
    end
  end

  before_validation do
    self.performed_on ||= Date.today
  end

  before_save do
    self.points = self.points_entered * self.multiple
  end

  before_create do
    if self.bailed == true
      entry_type = self.type_name
      message = "Bailed on #{entry_type} - #{self.performed_on}"
      flag = ClientFlag.create!(client_id: self.client.id,
                                created_by_id: self.added_by_id,
                                description: message,
                                can_shop: false,
                                expires_on: Date.today + 2.weeks)
    end
  end

  after_save do
    self.client.update_last_activity!
  end

  def bail_penalty
    self.class.bail_penalty
  end

  # how many PointsEntry objects  were +performed_on+ today?
  def self.daily_count
    PointsEntry.where('performed_on = ?', Date.today).count
  end

  # What is the extra points penalty for bailing on a chore?
  # TODO: Make this configurable
  def self.bail_penalty
    100
  end

end

app/models/points_entry_type.rb
require 'anonymizable'

class PointsEntryType < ActiveRecord::Base
  extend Anonymizable

  validates :name,
    presence: true,
    uniqueness: true

  has_many :points_entries
  has_many :signup_lists

  scope :active, -> { where(:is_active => true) }

  # Awkward side effect of the app's excel sheet ancestry
  def self.purchase
    where name: "Purchase"
  end

  def self.quicksearch(query)
    starts_with = "#{query}%"
    ends_with = "%#{query}"
    contains = "%#{query}%"
    where('(name = ? or name ilike ? or name ilike ? or name ilike ?) and is_active = true',
          query, starts_with, ends_with, contains)
      .order(:name)
  end

  anonymizes(:description) { Faker::Lorem.sentence }
  anonymizes :name do
    timings  = [ "All-Day", "Morning", "Afternoon", "Evening", "Overnight" ]
    locations = [
      "Kitchen",     "Meeting Room", "Elevator",
      "Dining Room", "Bathroom",     "Grounds",
      "Shower",      "Store",        "Office" ,
      "Garbage",     "Donations",    "Breakfast",
      "Lunch",       "Movie Room",   "Stairwell",
    ]
    tasks     = [
      "Setup", "Breakdown", "Sweep",
      "Mop",   "Clean",     "Vacuum",
      "Wipe",  "Put Away",  "Lease",
      "Prep",  "Dry",       "Monitor",
    ]

    descriptives = []
    if Random.rand.round == 0 then descriptives.push(timings.sample) end
    if Random.rand.round == 0 then descriptives.push(locations.sample) end
    descriptives.push tasks.sample
    descriptives.join ' '
  end
end

app/controllers/points_entries_controller.rb
# Allows users to log incentive points gained by performing chores,
# or points lost from purchases or bailing on chores.
class PointsEntriesController < ApplicationController
  before_filter :require_user

  # GET /points_entries
  def index
    load_points_entries
  end

  # GET /points_entries/1
  def show
    authorize! :show, PointsEntry
    load_points_entry
  end

  # GET /points_entries/new
  def new
    build_points_entry
  end

  # GET /points_entries/1/edit
  def edit
    load_points_entry
    build_points_entry
  end

  # POST /points_entries
  def create
    build_points_entry
    save_points_entry or render :new
  end

  # PUT /points_entries/1
  def update
    load_points_entry
    build_points_entry
    save_points_entry or render :edit
  end

  # DELETE /points_entries/1
  def destroy
    load_points_entry
    destroy_points_entry

    redirect_to points_entries_url
  end

  private

  def points_entry_params
    points_entry_params = params[:points_entry]

    if points_entry_params
      points_entry_params.permit(:client_id,
                                 :points_entry_type_id,
                                 :performed_on,
                                 :bailed,
                                 :added_by_id,
                                 :location_id,
                                 :multiple,
                                 :points_entered)
    else
      {}
    end
  end

  def load_points_entries
    @points_entries ||= PointsEntry.order("id DESC").page params[:page]
  end

  def load_points_entry
    @points_entry ||= PointsEntry.find(params[:id])
  end

  def build_points_entry
    @points_entry            ||= PointsEntry.new
    @points_entry.attributes   = points_entry_params
    @points_entry.added_by   ||= current_user

    if !@points_entry.client_id and submitted_alias = params[:current_alias]
      client = Client.where('current_alias = ?', submitted_alias).first
      @points_entry.client = client if client
    end

    if !@points_entry.points_entry_type_id and submitted_entry_type = params[:points_entry_type]
      entry_type = PointsEntryType.where(name: submitted_entry_type).first
      @points_entry.points_entry_type = entry_type if entry_type
    end
  end

  def save_points_entry
    if @points_entry.save
      redirect_to @points_entry,
        notice: 'Points entry was successfully created'
    end
  end

  def destroy_points_entry
    @points_entry.destroy
  end
end

app/views/points_entries/_as_table.html.haml
- hide ||= []
%table.table.table-striped.entries
  %thead
    %tr
      %th Performed On
      - unless hide.include? :client
        %th Client
      - unless hide.include? :points_entry_type
        %th Type
      %th Location
      %th Points
      - unless hide.include? :added_by
        %th Added By
      %th Actions
    %tbody
    - points_entries.each do |entry|
      %tr
        %td= entry.performed_on
        - unless hide.include? :client
          %td= link_to entry.client_current_alias, entry.client
        - unless hide.include? :points_entry_type
          %td= link_to entry.type_name, entry.points_entry_type
        %td= link_to entry.location_name, entry.location
        %td
          - if entry.bailed
            %span.text-error Bailed!
          = entry.points
        - unless hide.include? :added_by
          %td= link_to entry.added_by_login, entry.added_by
        %td
          = link_to "View", entry
          - if can? :manage, PointsEntry
            = link_to "Change", edit_points_entry_path(entry)
            = link_to "Remove", entry, method: :delete, confirm: "Are you sure?"

app/views/points_entries/_context_navigation.html.haml
%ul.nav.nav-tabs
  - if can? :create, PointsEntry
    %li= link_to 'New Entry', new_points_entry_path
  - if defined? points_entry
    - if can? :edit, points_entry
      %li= link_to "Edit", edit_points_entry_path(points_entry)
  - if can? :show, PointsEntryType
    %li.pull-right= link_to 'Entry Types', points_entry_types_path

app/views/points_entries/_form.html.haml
= form_for entry, role: 'form' do |f|
  - if entry.errors.any?
    #error_explanation
      %h2= pluralize entry.errors.count, "error"
      %ul
        - entry.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :client_id, class: 'control-label'
    = text_field_tag "current_alias", entry.client_current_alias,
      data: { provide: 'typeahead', field: 'points_entry_client_id', balance: 0 },
      autocomplete: 'off', autocapitalize: 'off', autocorrect: 'off',
      placeholder: 'The name they go by...',
      class: 'client-typeahead form-control'
    %span.hint
      - if entry.client_is_flagged
        %span.is-flagged
          %span.icon-flag
          - if !entry.client.can_shop?
            %span.label.label-danger No Shopping
          = link_to "flagged", flags_client_path(entry.client), class: "text-error"
      - else
        %span.is-flagged{ style: "display: none" }
          %span.icon-flag
          %span.label.label-danger.shopping-blocked-label{ style: "display: none" } No Shopping
          = link_to "flagged", '#', class: "text-error"
      %span.pull-right
        = link_to "Add Client", new_client_path
  .form-group
    = f.label :points_entry_type_id, class: 'control-label'
    = text_field_tag "points_entry_type", entry.type_name,
      data: { provide: 'typeahead', field: 'points_entry_points_entry_type_id', pointsfield: 'points_entry_points_entered' },
      autocomplete: 'off', autocapitalize: 'off', autocorrect: 'off',
      placeholder: 'What they did...',
      class: 'pointsentrytype-typeahead form-control'
  .checkbox
    = f.label :bailed do
      = f.check_box :bailed, 
        data: { field: 'points_entry_points_entered', penalty: entry.bail_penalty }, 
        class: 'bailed'
      Bailed
  .form-group
    .col-xs-2.well
      %span.point-balance.text-info= number_with_delimiter entry.client_point_balance
      +
    .col-xs-4
      = f.label :points, class: 'control-label'
      = f.number_field :points_entered, 
        data: { default: entry.type_default_points }, 
        placeholder: 'How many points gained or spent...',
        autocomplete: 'off', class: 'form-control'
    .col-xs-4
      x
      = f.label :multiple, class: 'control-label'
      = f.number_field :multiple,
        data: { default: 1 },
        autocomplete: 'off', class: 'form-control'
    .col-xs-2.well
      \=
      %span.new-balance.text-info
  .form-group
    = f.label :location_id
    = location_select f, :location_id, current_user
  - unless entry.new_record?
    .row
      .form-group
        = f.label :performed_on
        = f.date_select :performed_on, class: 'form-control'
  .form-group
    = f.hidden_field :client_id
    = f.hidden_field :points_entry_type_id
    = f.submit class: "btn btn-block btn-primary"
    = cancel_button

app/views/points_entries/_points_entry.html.haml
.summary
  .header
    = points_entry.performed_on
    = points_entry.client_current_alias
    = points_entry.points_entry_type_name
    = points_entry.points
  = link_to "Show", points_entry

app/views/points_entries/_sidebar.html.haml
%ul.nav.nav-tabs
  - if can? :create, PointsEntry
    %li= link_to 'New Entry', new_points_entry_path
  - if defined? points_entry
    - if can? :edit, points_entry
      %li= link_to "Edit", edit_points_entry_path(points_entry)
  - if can? :show, PointsEntryType
    %li.pull-right= link_to 'Entry Types', points_entry_types_path

app/views/points_entries/edit.html.haml
= content_for(:title) do
  Editing Log Entry

= content_for(:context_navigation) do
  = render 'context_navigation', points_entry: @points_entry

= render 'form', entry: @points_entry

app/views/points_entries/index.html.haml
= content_for(:title) do
  Points Log

= content_for(:context_navigation) do
  = render 'context_navigation'

= paginate @points_entries

= render 'as_table', points_entries: @points_entries

= paginate @points_entries

app/views/points_entries/new.html.haml
= content_for(:title) do
  Add Points Entry

= render 'form', entry: @points_entry

app/views/points_entries/show.html.haml
= content_for(:title) do
  Showing Entry

= content_for(:context_navigation) do
  = render 'context_navigation', points_entry: @points_entry

- if notice
  %p
    %span.label.label-info Info
    = @points_entry.client_current_alias
    now has
    = number_with_delimiter(@points_entry.client_point_balance)
    points

%dl.dl-horizontal
  %dt Client
  %dd= link_to @points_entry.client_current_alias, @points_entry.client
  %dt Location
  %dd= link_to @points_entry.location_name, @points_entry.location
  %dt Type
  %dd= link_to @points_entry.type_name, @points_entry.points_entry_type
  %dt Performed On
  %dd= @points_entry.performed_on
  %dt Points
  %dd
    - if @points_entry.multiple != 1
      = @points_entry.points_entered
      x
      = @points_entry.multiple
      \=
    = @points_entry.points
  - if @points_entry.bailed
    %dd
      %em (Bailed)
  %dt Added By
  %dd= link_to @points_entry.added_by_login, @points_entry.added_by