config/routes.rb
Marysplace::Application.routes.draw do

  resources :organizations

  resources :client_notes


  namespace :api, defaults: { format: :json } do
    namespace :v0 do
      resources :checkins, only: [ :create ]
    end
  end

  resources :locations

  resources :messages

  resources :roles, only: [ :show ]

  resources :client_flags do
    member do
      get 'resolve'
      post 'resolve_store'
    end

    collection do
      get 'resolved'
      get 'unresolved'
    end
  end

  resources :checkins do
    collection do
      get 'selfcheck'
      put 'selfcheck_post'
      get 'today'
      get 'report/:year/:month/:day' => 'checkins#daily_report',
        constraints: {
          year: %r/\d{4}/,
          month: %r/\d\d?/,
          day: %r/\d\d?/
        },
        as: 'daily_report'
      get 'report/:year/:month' => 'checkins#monthly_report',
        constraints: {
          year: %r/\d{4}/,
          month: %r/\d\d?/,
        },
        as: 'monthly_report'
      get 'report/:year' => 'checkins#annual_report',
        constraints: {
          year: %r/\d{4}/,
        },
        as: 'annual_report'
    end
  end

  resources :points_entries

  resources :points_entry_types do
    collection do
      get 'search'
      get 'all'
      get 'unpaged'
    end

    member do
      get 'entry'
      get 'report/:year/:month/:day' => 'points_entry_types#report',
        constraints: {
          year: %r/\d{4}/,
          month: %r/\d\d?/,
          day: %r/\d\d?/
        },
        as: 'daily_report'
      get 'report/:year/:month' => 'points_entry_types#report',
        constraints: {
          year: %r/\d{4}/,
          month: %r/\d\d?/,
        },
        as: 'monthly_report'
      get 'report/:year' => 'points_entry_types#report',
        constraints: {
          year: %r/\d{4}/,
        },
        as: 'annual_report'
      get 'report'
    end
  end

  resources :clients do
    collection do
      get 'all'
      get 'search'
    end

    member do
      get 'barcode'
      get 'card'
      post 'checkin_code'
      get 'checkins'
      get 'entries'
      get 'entry'
      get 'flags'
      get 'notes'
      get 'purchases'
    end
  end

  get "welcome/index"
  resources :users, except: [ :destroy ] do
    member do
      get  'entries'
      post 'preference'
    end
  end

  resources :password_resets,
    except: [ :destroy ]

  resource :user_session, only: [ :new, :create, :destroy ]

  get 'login' => 'user_sessions#new', as: :login
  delete 'logout' => 'user_sessions#destroy', as: :logout

  root :to => 'welcome#index'
end

app/models/client.rb
require 'anonymizable'
require 'zlib'
require 'barby'
require 'barby/outputter/svg_outputter'
require 'barby/barcode/code_128'

class Client < ActiveRecord::Base
  extend Anonymizable
  include HasBarcode

  has_barcode :barcode,
    outputter: :svg,
    type: Barby::Code128B,
    value: Proc.new { |c| c.checkin_code }

  def bare_barcode
    barcode = Barby::Code128B.new( self.checkin_code )
    svg_options = {
      height: 30,
      ymargin: 72,
      xmargin: 5
    }

    barcode.bars_to_path svg_options
  end

  validates :current_alias,
    presence: true,
    uniqueness: true
  validates :added_by_id,
    presence: true

  belongs_to :added_by,
    class_name: "User"
  belongs_to :last_edited_by,
    class_name: "User"
  belongs_to :login,
    class_name: "User"

  belongs_to :organization

  has_many :points_entries,
    dependent: :destroy
  has_many :checkins,
    dependent: :destroy
  has_many :flags,
    class_name: 'ClientFlag',
    dependent: :destroy
  has_many :staff_notes,
    class_name: 'ClientNote',
    dependent: :destroy

  delegate :login,
    to:     :added_by,
    prefix: true
  delegate :login,
    to: :last_edited_by,
    prefix: true

  # The generated barcode used for automated checkin
  def barcode(args={})
    self.bare_barcode
  end

  # The generated code used for automated checkin
  def login_code
    self.login.login
  end

  def update_last_activity
    if self.created_at
      last_activity_on = self.last_activity_on || self.created_at.to_date
    end

    latest_entry = self.points_entries.order('performed_on DESC').first

    if latest_entry and latest_entry.performed_on > last_activity_on
      last_activity_on = latest_entry.performed_on
    end

    if self.last_activity_on and last_activity_on <= self.last_activity_on
      # Nothing to change
      return
    end

    self.last_activity_on = last_activity_on
  end

  def update_last_activity!
    self.update_last_activity
    self.save!
  end

  before_save do
    self.point_balance ||= 0

    unless self.organization
      if self.added_by.organization
        self.organization = self.added_by.organization
      end
    end
  end

  before_create do
    self.last_activity_on = Date.today
  end

  # Generate a sufficiently unique checkin code
  #
  # short enough to type, but not just straight current_alias
  # (which can change)
  def generate_checkin_code
    source = "RE|#{self.current_alias}|#{Time.now.to_i}"
    login_code = sprintf "%08x", Zlib.crc32(source)
    return login_code
  end

  def update_checkin_code!
    self.update_attributes checkin_code: self.generate_checkin_code
  end

  # Does this client have unresolved flags?
  def is_flagged?
    return self.flags.unresolved.count > 0
  end

  # Can this client make purchases?
  def can_shop?
    if self.flags.unresolved.where(can_shop: false).count > 0
      return false
    end

    return true unless self.has_shopped?

    now = Time.now
    if self.last_shopped_at < now.beginning_of_week
      return true
    end

    return false
  end

  # Should this client be blocked from entry?
  def is_blocked?
    return self.flags.unresolved.where(is_blocking: true).count > 0
  end

  # Have I ever shopped?
  def has_shopped?
    self.points_entries.purchases.count > 0
  end

  # When was my last completed shopping trip?
  def last_shopped_at
    if self.has_shopped?
      self.points_entries.purchases.last.performed_on.to_time
    end
  end

  def to_hash
    { id: self.id,
      current_alias: self.current_alias,
      other_aliases: self.other_aliases,
      point_balance: self.point_balance,
      is_flagged:    self.is_flagged?,
      can_shop:      self.can_shop?
    }
  end

  def update_points!
    latest_balance = self.points_entries.sum(:points)
    self.update_attributes point_balance: latest_balance
  end

  def self.filtered_by filters

    if filters.nil?
      filters = { is_active: true }
    else
      filters.delete_if { |k,v| v.empty? }
    end

    filtered = self
    if is_active = filters[:is_active]
      filtered = filtered.where(is_active: is_active)
    else
      filtered = filtered.where(is_active: true)
    end

    return filtered
  end

  def self.quicksearch(query)
    unless query
      return []
    end

    query        = query.strip
    starts_with  = "#{query}%"
    ends_with    = "%#{query}"
    contains     = "%#{query}%"
    sql_fragment = %{
      (current_alias = ?
       or current_alias ilike ?
       or current_alias ilike ?
       or current_alias ilike ?
       or other_aliases ilike ?
       or other_aliases ilike ?
       or other_aliases ilike ?)
      and is_active = true
    }

    where(sql_fragment,
      query, starts_with, ends_with, contains, starts_with, ends_with,
      contains)
      .order(:current_alias)
  end

  # Fill my identifying fields with fake data
  #
  # Replaces fields in the client but does not save them. That allows the one
  # "maybe" production usage: anonymized display of clients.
  anonymizes(:full_name) { Faker::Name.name }

  anonymizes :oriented_on do |client|
    if client.points_entries.size > 0
      client.points_entries.order(:performed_on).last.performed_on
    end
  end

  anonymizes(:phone_number) { Faker::PhoneNumber.phone_number }

  anonymizes :birthday do
    # Reasonable age range is 18-90.
    # TODO: simulate clients that are children of other clients.
    age = Random.rand(18..90)
    offset = Random.rand(0..365) # So everyone doesn't magically share the same birthday
    age.years.ago + offset.days
  end

  anonymizes(:notes) { Faker::Lorem.paragraphs(Random.rand(0..3)).join }

  anonymizes :current_alias  do |client|
    names = client.full_name.split ' '
    usual_pattern = "#{names.shift} " + names.map { |name| "#{name[0]}." }.join(' ')
    if Client.where(current_alias: usual_pattern).count == 0
      usual_pattern
    elsif Client.where(current_alias: client.full_name).count == 0
      client.full_name
    else
      "#{client.full_name} #{client.id}"
    end
  end

  anonymizes(:other_aliases) { '' }
end

app/models/client/filtered.rb
class Client::Filtered < ActiveType::Object
  attribute :is_active, :boolean
end

app/controllers/clients_controller.rb
require 'open-uri'

# Finding and CRUDing clients
class ClientsController < ApplicationController
  before_filter :require_user
  authorize_resource
  helper_method :sort_column, :sort_direction

  # GET /all
  # GET /all.json
  def all
    load_clients
    load_preferences
  end

  # GET /clients
  # GET /clients.json
  def index
    load_clients
    load_preferences
  end

  # GET /search
  # GET /search.json
  def search
    find_clients
    render_clients
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    load_client
  end

  # GET /clients/new
  # GET /clients/new.json
  def new
    build_client
  end

  def entry
    load_client
    build_points_entry
  end

  # GET /clients/1/edit
  def edit
    authorize! :update, Client
    load_client
  end

  # POST /clients
  # POST /clients.json
  def create
    authorize! :create, Client
    build_client
    save_client or render :new
  end

  # PUT /clients/1
  # PUT /clients/1.json
  def update
    authorize! :update, Client
    load_client
    build_client
    save_client or render :edit
  end

  def checkin_code
    authorize! :manage, Client
    load_client
    update_client_checkin_code
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    authorize! :destroy, Client
    load_client
    destroy_client

    redirect_to clients_url
  end

  # GET /clients/1/entries
  # GET /clients/1/entries.json
  def entries
    load_client
    load_entries
    load_preferences
  end

  def checkins
    authorize! :show, Checkin
    load_client
    load_checkins
  end

  def flags
    authorize! :show, ClientFlag
    load_client
    load_flags
  end

  def barcode
    authorize! :show, Client
    load_client
  end

  def card
    authorize! :manage, Client

    load_client
    load_card_picture
    render_card
  end

  def purchases
    authorize! :show, Client
    load_client
  end

  private

  def client_params
    client_params = params[:client]

    if client_params
      client_params.permit(:current_alias,
                           :full_name,
                           :other_aliases,
                           :oriented_on,
                           :birthday,
                           :phone_number,
                           :notes,
                           :is_active,
                           :organization_id,
                           :case_manager_info,
                           :family_info,
                           :community_goal,
                           :email_address,
                           :emergency_contact,
                           :medical_info,
                           :mailing_list_address,
                           :personal_goal,
                           :signed_covenant,
                           :staying_at,
                           :on_mailing_list,
                           :picture,
                           :picture_file_name)
    else
      {}
    end
  end

  def load_clients
    sort_rule = "#{sort_column} #{sort_direction}"
    @clients ||= Client.filtered_by(params[:filters])
        .order(sort_rule).page params[:page]
  end

  def find_clients
    @query ||= params[:q]
    @clients = Client.quicksearch @query
  end

  def load_client
    @client ||= Client.find params[:id]
  end

  def build_client
    @client ||= Client.new
    @client.attributes = client_params
    @client.added_by ||= current_user
  end

  def render_clients
    respond_to do |format|
      format.html # search.html.haml
      format.json {
        render json: @clients.map { |client| client.to_hash }
      }
    end
  end

  def save_client
    if @client.save
      redirect_to @client
    end
  end

  def destroy_client
    @client.destroy
  end

  def update_client_checkin_code
    @client.update_checkin_code!
    redirect_to @client
  end

  def load_preferences
    @prefs ||= current_user.preference_for :client_fields
  end

  def load_entries
    @entries ||= @client.points_entries.page params[:page]
  end

  def load_checkins
    @checkins = @client.checkins.order('checkin_at DESC').page params[:page]
  end

  def load_flags
    @flags = @client.flags.order('expires_on DESC')
  end

  def load_card_picture
    @picture_url = if @client.picture_file_name
                     @client.picture.url(:square)
                   else
                      "https://s3.amazonaws.com/elasticbeanstalk-us-east-1-820256515611/" +
                      "marys-place/avatars/thumb/blank.png"
                   end
  end

  def render_card
    respond_to do |format|
      if @client.checkin_code
        format.svg
        format.html { render layout: 'card' }
      else
        flash[:error] = "#{@client.current_alias} has no login yet."
        redirect_to @client
      end
    end
  end

  def sort_column
    default = "current_alias"
    return default unless params[:sort]

    Client.column_names.include?(params[:sort]) ?
      params[:sort] : "current_alias"
  end

  def sort_direction
    default = "asc"
    return default unless params[:direction]

    %{asc desc}.include?(params[:direction]) ? params[:direction] : "asc"
  end

  def build_points_entry
    @points_entry ||= PointsEntry.new
    @points_entry_type ||= PointsEntryType.new
    @points_entry.client ||= @client
  end
end

app/views/clients/_as_table.html.erb
<% prefs = current_user.preference_for(:client_fields) %>

<table class="table">
  <thead>
    <tr>
      <th><%= sortable "current_alias" %></th>
      <% if can? :manage, Client %>
        <% if prefs.include? "full_name" %>
          <th><%= sortable "full_name" %></th>
        <% end %>
        <% if prefs.include? "point_balance" %>
          <th><%= sortable "point_balance" %></td>
        <% end %>
        <% if prefs.include? "created_at" %>
          <th><%= sortable "created_at" %></th>
        <% end %>
        <% if prefs.include? "oriented_on" %>
          <th><%= sortable "oriented_on" %></th>
        <% end %>
        <% if prefs.include? "last_activity_on" %>
          <th><%= sortable "last_activity_on" %></th>
        <% end %>
        <% if prefs.include? "birthday" %>
          <th><%= sortable "birthday" %></th>
        <% end %>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <%= render clients, prefs: prefs %>
  </tbody>
</table>

app/views/clients/_form.html.haml
= form_for client, role: 'form' do |f|
  - if client.errors.any?
    .error_explanation
      %h3= pluralize client.errors.count, "Error"
      %ul
        - client.errors.full_messages.each do |msg|
          %li= msg
  .tab-content
    #client-general.tab-pane.active
      .row
        .col-md-6
          = f.hidden_field :added_by_id
          = f.hidden_field :last_edited_by_id
          .form-group
            = f.label :current_alias
            = f.text_field :current_alias, class: 'form-control'
        .col-md-6
          .form-group
            = f.label :full_name
            = f.text_field :full_name, class: 'form-control'
      .row
        .col-md-6
          .form-group
            = f.label :other_aliases
            = f.text_field :other_aliases, class: 'form-control'
        .col-md-6
          .form-group
            = f.label :birthday
            = f.date_field :birthday, class: 'form-control'
      .row
        .col-md-6
          .checkbox
            = f.label :is_active do
              = f.check_box :is_active
              Is currently active?
      .row
        .col-md-12
          .form-group
            = f.label :notes
            = f.text_area :notes, class: 'form-control'
  .row
    .col-md-12
      .form-group
        = f.submit class: "btn btn-primary btn-block"
        = cancel_button

app/views/clients/_sidebar.html.haml
%ul.nav.nav-tabs
  - if defined?(client) and client.id
    - if can? :show, PointsEntry
      %li= link_to "Points Log", entries_client_path(client)
    - if can? :show, Checkin
      %li= link_to "Checkins", checkins_client_path(client)
    - if can? :show, ClientFlag
      %li= link_to "Flags", flags_client_path(client)
    - if can? :show, StoreCart
      %li= link_to "Purchases", purchases_client_path(client)
    - if can? :create, PointsEntry
      %li= link_to "Log Points for #{client.current_alias}", entry_client_path(client)
    - if can? :edit, client
      %li= link_to "Edit #{client.current_alias}", edit_client_path(client)
    - if client.login and can? :show, User
      %li= link_to "ID Card for #{client.current_alias}", card_client_path(client)
  - if can? :create, Client
    %li= link_to "Create New Client", new_client_path

app/views/clients/card.html.haml
%div.id-card
  %div.main
    %div.text
      %p.text= @client.current_alias
      %p= @client.barcode(height: 40, margin: 5).html_safe
      %p.text= @client.checkin_code
    %div.pic
      = image_tag @client.picture.url(:square), class: "avatar"

app/views/clients/edit.html.haml
= content_for(:title) do
  Editing
  = @client.current_alias

= content_for(:context_navigation) do
  = render 'context_navigation', client: @client

= render 'form', client: @client

app/views/clients/entries.html.haml
= content_for(:title) do
  Points Entries for
  = @client.current_alias

= content_for(:context_navigation) do
  = render 'context_navigation', client: @client

= render @client

%h2 Entries

= paginate @entries

= render 'points_entries/as_table', points_entries: @entries, prefs: @prefs,
  hide: [ :client ]

= paginate @entries

app/views/clients/entry.html.haml
= content_for(:title) do
  Log Points for
  = @client.current_alias

=content_for(:context_navigation) do
  = render 'context_navigation', client: @client

= render 'points_entries/form',
  client: @client, entry: @points_entry,
  points_entry_type: @points_entry_type,
  bail_penalty: PointsEntry.bail_penalty, locations: Location.all,
  default_location: Location.default_location_for(current_user)

app/views/clients/flags.html.haml
= content_for(:title) do
  Flag History for
  = @client.current_alias


= content_for(:context_navigation) do
  = render 'context_navigation', client: @client

%table.table
  = render @flags

app/views/clients/index.html.erb
<% content_for(:title) do %>Active Clients<% end %>

<% content_for(:context_navigation) do %><%= render 'context_navigation' %><% end %>

<%= render 'clients/search_form', search_query: @query %>

<div class="row">
  <div class="col-xs-12 col-sm-6 text-left">
    <p><%= page_entries_info @clients %></p>
    <%= paginate @clients %>
  </div>
  <div class="col-xs-12 col-sm-6 text-right">
    <%= render 'filters', filters: @filters %>
    <%= render 'preferences', prefs: @prefs %>
  </div>
</div>

<%= render 'as_table', clients: @clients %>

<%= paginate @clients %>

app/views/clients/new_login.html.haml
= content_for(:title) do
  Create Login for #{@client.current_alias}

=content_for(:context_navigation) do
  = render 'context_navigation', client: @client

%p
  Please use the form below to provide a password.

= form_tag(create_login_client_path(@client), method: "PUT") do
  = hidden_field_tag(:client_id, @client)
  %fieldset
    .control-group
      = label_tag(:password, "Password:")
      = password_field_tag(:password)
    .control-group
      = label_tag(:password_confirmation, "Confirm:")
      = password_field_tag(:password_confirmation)
    = submit_tag "Save", class: "btn"

app/views/clients/purchases.html.haml
= content_for(:title) do
  #{@client.current_alias} Purchases

= content_for(:context_navigation) do
  = render 'context_navigation', client: @client

- if @client.is_shopping?
  %p #{@client.current_alias} has an open cart
- else
  %p= link_to "Start Shopping", store_start_path(shopper_id: @client), method: :put, class: "btn",
    data: { confirm: "Start a cart for #{@client.current_alias}?" }

%table.table
  = render @carts

app/views/clients/search.html.haml
= content_for(:title) do
  Clients

= content_for(:context_navigation) do
  = render 'context_navigation'

= render 'clients/search_form', search_query: @query

%table.table
  %thead
    %tr
      %th= sortable "current_alias"
      - if can? :manage, Client
        %th= sortable "point_balance"
        %th= sortable "created_at"
  %tbody
    = render @clients

app/views/clients/show.html.haml
= content_for(:title) do
  = @client.current_alias

= content_for(:context_navigation) do
  =render 'context_navigation', client: @client

.panel.panel-default
  .panel-body
    .panel
      .panel-body.tab-content
        #client-general.tab-pane.active
          .row
            .col-md-6
              .panel.panel-default
                .panel-heading
                  %h3.panel-title
                    Current Alias
                .panel-body
                  - unless @client.is_active
                    %span.label.label-info Inactive
                  - if @client.is_blocked?
                    %span.label.label-danger Blocked
                  = @client.current_alias
            .col-md-6
              .panel.panel-default
                .panel-heading
                  %h3.panel-title
                    Full Name
                .panel-body= @client.full_name || 'Not Given'
          .row
            .col-md-6
              .panel.panel-default
                .panel-heading
                  %h3.panel-title
                    Point Balance
                .panel-body= number_with_delimiter @client.point_balance
            .col-md-6
              .panel.panel-default
                .panel-heading
                  %h3.panel-title
                    Last Activity On
                .panel-body
                  = @client.last_activity_on
          .row
            .col-md-6
              .panel.panel-default
                .panel-heading
                  %h3.panel-title
                    Added By
                .panel-body
                  = link_to @client.added_by_login, @client.added_by
            - if @client.birthday
              .col-md-6
                .panel.panel-default
                  .panel-heading
                    %h3.panel-title
                      Birthday
                  .panel-body
                    = @client.birthday
          - if @client.other_aliases != ''
            .row
              .col-md-12
                .panel.panel-default
                  .panel-heading
                    %h3.panel-title
                      Other Aliases
                  .panel-body
                    = @client.other_aliases
          - if @client.notes != ''
            .row
              .col-md-12
                .panel.panel-default
                  .panel-heading
                    %h3.panel-title
                      Notes
                  .panel-body
                    = @client.notes