config/routes.rb
Marysplace::Application.routes.draw do

  resources :organizations

  resources :client_notes


  namespace :api, defaults: { format: :json } do
    namespace :v0 do
      resources :checkins, only: [ :create ]
    end
  end

  resources :locations

  resources :messages

  resources :roles, only: [ :show ]

  resources :client_flags do
    member do
      get 'resolve'
      post 'resolve_store'
    end

    collection do
      get 'resolved'
      get 'unresolved'
    end
  end

  resources :checkins do
    collection do
      get 'selfcheck'
      put 'selfcheck_post'
      get 'today'
      get 'report/:year/:month/:day' => 'checkins#daily_report',
        constraints: {
          year: %r/\d{4}/,
          month: %r/\d\d?/,
          day: %r/\d\d?/
        },
        as: 'daily_report'
      get 'report/:year/:month' => 'checkins#monthly_report',
        constraints: {
          year: %r/\d{4}/,
          month: %r/\d\d?/,
        },
        as: 'monthly_report'
      get 'report/:year' => 'checkins#annual_report',
        constraints: {
          year: %r/\d{4}/,
        },
        as: 'annual_report'
    end
  end

  resources :points_entries

  resources :points_entry_types do
    collection do
      get 'search'
      get 'all'
      get 'unpaged'
    end

    member do
      get 'entry'
      get 'report/:year/:month/:day' => 'points_entry_types#report',
        constraints: {
          year: %r/\d{4}/,
          month: %r/\d\d?/,
          day: %r/\d\d?/
        },
        as: 'daily_report'
      get 'report/:year/:month' => 'points_entry_types#report',
        constraints: {
          year: %r/\d{4}/,
          month: %r/\d\d?/,
        },
        as: 'monthly_report'
      get 'report/:year' => 'points_entry_types#report',
        constraints: {
          year: %r/\d{4}/,
        },
        as: 'annual_report'
      get 'report'
    end
  end

  resources :clients do
    collection do
      get 'all'
      get 'search'
    end

    member do
      get 'barcode'
      get 'card'
      post 'checkin_code'
      get 'checkins'
      get 'entries'
      get 'entry'
      get 'flags'
      get 'notes'
      get 'purchases'
    end
  end

  get "welcome/index"
  resources :users, except: [ :destroy ] do
    member do
      get  'entries'
      post 'preference'
    end
  end

  resources :password_resets,
    except: [ :destroy ]

  resource :user_session, only: [ :new, :create, :destroy ]

  get 'login' => 'user_sessions#new', as: :login
  delete 'logout' => 'user_sessions#destroy', as: :logout

  root :to => 'welcome#index'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_filter :require_user

  def index
    @active_flag_count = ClientFlag.active_count
    @checkin_count = Checkin.today.count
    @entry_count   = PointsEntry.daily_count

    if current_user.email.blank? and !session[:email_alert_shown]
      @email_alert_needed = true
      session[:email_alert_shown] = true
    end
  end
end

app/views/welcome/_alerts.html.erb
<% if email_alert_needed %>
  <div class="alert">
    <p>We need an email address to complete
    <%= link_to 'your account information', edit_user_path( current_user ) %>.
    It will not be shared with anybody outside of Mary's Place.
    </p>
  </div>
<% end %>

app/views/welcome/_client_flags.html.erb
<% if can? :show, ClientFlag %>
  <h1><%= active_flag_count %></h1>
  <p class="small">Active Flags</p>
  <ul class="nav nav-pills nav-stacked">
    <li><%= link_to "Show Active Flags", unresolved_client_flags_path %></li>
    <% if can? :create, ClientFlag %>
      <li><%= link_to "Add Flag", new_client_flag_path %></li>
    <% end %>
  </ul>
<% end %>

app/views/welcome/_entry_points.html.erb
<% if can? :show, PointsEntry %>
  <h1><%= @entry_count %></h1>
  <p class="small">Points entries logged today</p>
  <ul class="nav nav-pills nav-stacked">
    <li><%= link_to "Show Points Log", points_entries_path %></li>
    <% if can? :create, PointsEntry %>
      <li><%= link_to "Enter Points", new_points_entry_path %></li>
    <% end %>
  </ul>
<% end %>

app/views/welcome/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div>
      <%= render 'alerts', email_alert_needed: @email_alert_needed %>
      <%= render 'clients/search_form' %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-18 col-sm-6 text-center">
      <div class="panel panel-default">
        <%= render 'entry_points' %>
      </div>
    </div>
    <div class="col-xs-18 col-sm-6 text-center">
      <div class="panel panel-default">
        <%= render 'client_flags', active_flag_count: @active_flag_count %>
      </div>
    </div>
  </div>
</div>