config/routes.rb
Marysplace::Application.routes.draw do

  resources :organizations

  resources :client_notes


  namespace :api, defaults: { format: :json } do
    namespace :v0 do
      resources :checkins, only: [ :create ]
    end
  end

  resources :locations

  resources :messages

  resources :roles, only: [ :show ]

  resources :client_flags do
    member do
      get 'resolve'
      post 'resolve_store'
    end

    collection do
      get 'resolved'
      get 'unresolved'
    end
  end

  resources :checkins do
    collection do
      get 'selfcheck'
      put 'selfcheck_post'
      get 'today'
      get 'report/:year/:month/:day' => 'checkins#daily_report',
        constraints: {
          year: %r/\d{4}/,
          month: %r/\d\d?/,
          day: %r/\d\d?/
        },
        as: 'daily_report'
      get 'report/:year/:month' => 'checkins#monthly_report',
        constraints: {
          year: %r/\d{4}/,
          month: %r/\d\d?/,
        },
        as: 'monthly_report'
      get 'report/:year' => 'checkins#annual_report',
        constraints: {
          year: %r/\d{4}/,
        },
        as: 'annual_report'
    end
  end

  resources :points_entries

  resources :points_entry_types do
    collection do
      get 'search'
      get 'all'
      get 'unpaged'
    end

    member do
      get 'entry'
      get 'report/:year/:month/:day' => 'points_entry_types#report',
        constraints: {
          year: %r/\d{4}/,
          month: %r/\d\d?/,
          day: %r/\d\d?/
        },
        as: 'daily_report'
      get 'report/:year/:month' => 'points_entry_types#report',
        constraints: {
          year: %r/\d{4}/,
          month: %r/\d\d?/,
        },
        as: 'monthly_report'
      get 'report/:year' => 'points_entry_types#report',
        constraints: {
          year: %r/\d{4}/,
        },
        as: 'annual_report'
      get 'report'
    end
  end

  resources :clients do
    collection do
      get 'all'
      get 'search'
    end

    member do
      get 'barcode'
      get 'card'
      post 'checkin_code'
      get 'checkins'
      get 'entries'
      get 'entry'
      get 'flags'
      get 'notes'
      get 'purchases'
    end
  end

  get "welcome/index"
  resources :users, except: [ :destroy ] do
    member do
      get  'entries'
      post 'preference'
    end
  end

  resources :password_resets,
    except: [ :destroy ]

  resource :user_session, only: [ :new, :create, :destroy ]

  get 'login' => 'user_sessions#new', as: :login
  delete 'logout' => 'user_sessions#destroy', as: :logout

  root :to => 'welcome#index'
end

app/models/client_flag.rb
require 'anonymizable'

class ClientFlag < ActiveRecord::Base
  extend Anonymizable

  belongs_to :client
  belongs_to :created_by,
    class_name: "User"
  belongs_to :resolved_by,
    class_name: "User"

  validates :client,
    presence: true
  validates :created_by,
    presence: true

  default_scope { order 'created_at DESC' }

  scope :resolved, -> {
    where(["resolved_on is not null or expires_on <= ?", Date.today])
  }

  scope :unresolved, -> {
    where([
      "(resolved_on is null) and (expires_on is null or expires_on > ?)",
      Date.today
    ])
  }

  delegate :current_alias,
    to:     :client,
    prefix: true
  delegate :login,
    to:     :created_by,
    prefix: true
  delegate :login,
    to:     :resolved_by,
    prefix: true

  def self.active_count
    unresolved.count
  end

  def is_resolved?
    today = Date.today

    if self.resolved_on and self.resolved_on <= today
      return true
    end

    if self.expires_on and self.expires_on <= today
      return true
    end

    return false
  end

  after_save do
    if self.is_resolved?
      if self.client.is_flagged == true
        self.client.update_attributes is_flagged: false
      end
    else
      if self.client.is_flagged == false
        self.client.update_attributes is_flagged: true
      end
    end
  end

  anonymizes(:consequence)     { Faker::Lorem.paragraph }
  anonymizes(:action_required) { Faker::Lorem.paragraph }

  anonymizes :description do |flag|
    # Let some automatically generated descriptions pass.
    if flag.description =~ /^Bailed on .+ ([-\d]+)$/
      "Bailed on chore #{$1}"
    else
      Faker::Lorem.paragraph
    end
  end
end

app/controllers/client_flags_controller.rb
# Routes for client flags - issues that affect client usage of resources
class ClientFlagsController < ApplicationController
  before_filter :require_user

  # GET /client_flags
  def index
    authorize! :show, ClientFlag
    load_client_flags
  end

  # GET /client_flags/resolved
  def resolved
    authorize! :show, ClientFlag
    load_resolved_client_flags
  end

  def unresolved
    authorize! :show, ClientFlag
    load_unresolved_client_flags
  end

  # GET /client_flags/1
  def show
    authorize! :show, ClientFlag
    load_client_flag
  end

  # GET /client_flags/new
  def new
    authorize! :create, ClientFlag
    build_client_flag
  end

  # GET /client_flags/1/edit
  def edit
    authorize! :edit, ClientFlag
    load_client_flag
  end

  # POST /client_flags
  def create
    authorize! :create, ClientFlag
    build_client_flag
    save_client_flag or render :new
  end

  # PUT /client_flags/1
  def update
    authorize! :update, ClientFlag
    load_client_flag
    build_client_flag
    save_client_flag or render :edit
  end

  # DELETE /client_flags/1
  def destroy
    authorize! :destroy, ClientFlag
    load_client_flag
    destroy_client_flag
    redirect_to client_flags_url
  end

  def resolve
    load_client_flag
  end

  def resolve_store
    load_client_flag
    resolve_client_flag
  end

  private

  def client_flag_params
    client_flag_params = params[:client_flag]

    if client_flag_params
      client_flag_params.permit(:client_id,
                                :is_blocking,
                                :can_shop,
                                :expires_on,
                                :description,
                                :consequence,
                                :action_required)
    else
      {}
    end
  end

  def load_client_flags
    @client_flags ||= ClientFlag.page params[:page]
  end

  def load_resolved_client_flags
    @client_flags ||= ClientFlag.resolved.page params[:page]
  end

  def load_unresolved_client_flags
    @client_flags ||= ClientFlag.unresolved.page params[:page]
  end

  def load_client_flag
    @client_flag ||= ClientFlag.find(params[:id])
  end

  def build_client_flag
    @client_flag ||= ClientFlag.new
    @client_flag.attributes ||= client_flag_params
  end

  def save_client_flag
    @client_flag.created_by ||= current_user

    if @client_flag.save
      redirect_to @client_flag
    end
  end

  def destroy_client_flag
    @client_flag.destroy
  end

  def resolve_client_flag
    @client_flag.resolved_by = current_user
    @client_flag.resolved_on = Date.today

    if @client_flag.save
      redirect_to @client_flag,
        notice: "Issue was resolved"
    else
      redirect_to @client_flag,
        notice: "Unable to resolve issue."
    end
  end
end

app/helpers/client_flags_helper.rb
module ClientFlagsHelper
  # Build a table row for rendering this flag
  #
  # Uses Twitter Bootstrap CSS classes
  def row_for_client_flag(client_flag)
    if client_flag.is_resolved?
      row_class = "success"
    elsif client_flag.is_blocking
      row_class = "danger"
    end

    if row_class
      haml_tag :tr, class: row_class do
        yield
      end
    else
      haml_tag :tr do
        yield
      end
    end
  end
end

app/views/client_flags/_client_flag.html.haml
- row_for_client_flag(client_flag) do
  %td
    - if client_flag.is_resolved?
      %span.label.label-success
        - if client_flag.resolved_on
          Resolved by #{client_flag.resolved_by_login}
        - elsif client_flag.expires_on
          Expired on #{client_flag.expires_on}
    - elsif client_flag.is_blocking
      %span.label.label-danger
        - if client_flag.expires_on
          No entry until #{client_flag.expires_on}
        - else
          No entry
    - elsif client_flag.can_shop
      %span.label.label-default
        Expires on #{client_flag.expires_on}
    - elsif client_flag.expires_on
      %span.label.label-warning
        - if client_flag.expires_on
          No shopping until #{client_flag.expires_on}
        - else
          No shopping
  %td= client_flag.client_current_alias
  %td #{client_flag.created_at.to_date} by #{client_flag.created_by_login}
  %td= link_to "Show", client_flag

app/views/client_flags/_context_navigation.html.haml
%ul.nav.nav-tabs
  %li= link_to "All Flags", client_flags_path
  %li= link_to "Active Flags", unresolved_client_flags_path
  %li= link_to "Resolved Flags", resolved_client_flags_path
  - if can? :manage, ClientFlag
    - if defined? client_flag
      %li= link_to "Change", edit_client_flag_path(client_flag)
    %li= link_to "Add Flag", new_client_flag_path

app/views/client_flags/_form.html.haml
= form_for client_flag, role: 'form'  do |f|
  -if client_flag.errors.any?
    #error_explanation
      %h2= "#{pluralize(client_flag.errors.count, "error")} prohibited this client_flag from being saved:"
      %ul
        - client_flag.errors.full_messages.each do |msg|
          %li= msg
  .row
    .col-md-4
      .form-group
        = f.label :client_id
        - if client_flag.client
          = text_field_tag "current_alias", client_flag.client_current_alias,
            data: { provide: 'typeahead', field: 'client_flag_client_id' },
            class: 'client-typeahead form-control'
        - else
          = text_field_tag "current_alias", nil,
            data: { provide: 'typeahead', field: 'client_flag_client_id' },
            class: 'client-typeahead form-control'
        = f.hidden_field :client_id
    .col-md-4
      .checkbox
        = f.label :is_blocking do
          = f.check_box :is_blocking
          Should not enter?
      .checkbox
        = f.label :can_shop do
          = f.check_box :can_shop
          Still allowed to shop?
    .col-md-4
      .form-group
        = f.label :expires_on
        = f.date_select :expires_on, include_blank: true
  .row
    .col-md-4
      #flag-description-control.form-group
        = f.label :description
        = f.text_area :description, class: 'form-control'
    .col-md-4
      #flag-consequence-control.form-group
        = f.label :consequence
        = f.text_area :consequence, class: 'form-control'
    .col-md-4
      #flag-action-required-control.form-group
        = f.label :action_required
        = f.text_area :action_required, class: 'form-control'
  = f.submit 'Save', class: 'btn btn-primary btn-block'

app/views/client_flags/_sidebar.html.haml
%ul.nav.nav-tabs
  %li= link_to "All Flags", client_flags_path
  %li= link_to "Resolved Flags", resolved_client_flags_path
  %li= link_to "Unresolved Flags", unresolved_client_flags_path
  - if can? :manage, ClientFlag
    - if defined? client_flag
      %li= link_to "Change", edit_client_flag_path(client_flag)
    %li= link_to "Add Flag", new_client_flag_path

app/views/client_flags/edit.html.haml
= content_for :title do
  Editing Flag

= content_for :context_navigation do
  = render 'context_navigation', client_flag: @client_flag

= render 'form', client_flag: @client_flag

app/views/client_flags/index.html.haml
= content_for(:title) do
  Client Flags

= content_for(:context_navigation) do
  = render 'context_navigation'

= paginate @client_flags

%table.table
  = render @client_flags

= paginate @client_flags

app/views/client_flags/new.html.haml
= content_for(:title) do
  Add Client Flag

= content_for :context_navigation do
  = render 'context_navigation'

= render 'form', client_flag: @client_flag

app/views/client_flags/resolve.html.haml
= content_for(:title) do
  Resolve Flag

= content_for(:context_navigation) do
  = render 'context_navigation', client_flag: @client_flag

= form_tag(resolve_store_client_flag_path(@client_flag), method: :post, class: "form") do
  .control-group
    %label.control-label{ for: "resolution" } Resolution
    .controls
      %textarea{name: "resolution"}
      %span.help-block
        %em (Optional)
        description of resolution
    .form-actions
      %button.btn.btn-primary{ type: "submit" } Resolve

app/views/client_flags/resolved.html.haml
= content_for(:title) do
  Resolved Client Flags

= content_for(:context_navigation) do
  = render 'context_navigation'

= paginate @client_flags

%table.table
  = render @client_flags

= paginate @client_flags

app/views/client_flags/show.html.haml
= content_for(:title) do
  Flag for
  = @client_flag.client_current_alias

=content_for(:context_navigation) do
  = render 'context_navigation', client_flag: @client_flag

%dl.dl-horizontal
  %dt Client
  %dd= link_to @client_flag.client_current_alias, @client_flag.client
  %dt Created
  %dd
    = l(@client_flag.created_at, format: :long)
    by
    = link_to @client_flag.created_by_login, @client_flag.created_by
  %dt Description
  %dd= @client_flag.description || 'None Given'
  %dt Consequence
  %dd= @client_flag.consequence || 'None Given'
  %dt Action Required
  %dd= @client_flag.action_required || 'None Given'
  %dt Expires On
  %dd
    - if @client_flag.expires_on
      = l(@client_flag.expires_on, format: :long)
    - else
      No expiration
  %dt Notes
  %dd
    = @client_flag.client_current_alias
    - if @client_flag.is_blocking
      may not enter while this flag is unresolved.
    - else
      is not prevented from entering by this flag.
  %dd
    = @client_flag.client_current_alias
    - if @client_flag.can_shop
      is not prevented from shopping by this flag.
    - else
      may not shop while this flag is unresolved.
  - if @client_flag.resolved_on
    %dt Resolved
    %dd
      = l(@client_flag.resolved_on, format: :long)
      by
      = link_to @client_flag.resolved_by_login, @client_flag.resolved_by
    %dt Resolution
    %dd= @client_flag.resolution || 'None given'
  - else
    %dt Resolve
    %dd= link_to "Resolve", resolve_client_flag_path(@client_flag)

app/views/client_flags/unresolved.html.haml
= content_for(:title) do
  Active Client Flags

= content_for(:context_navigation) do
  = render 'context_navigation'

= paginate @client_flags

%table.table
  = render @client_flags

= paginate @client_flags